name: ci

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run lint
      run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run tests
      run: yarn test
